#!/bin/bash

echo "* Update and upgrade your system"

sudo apt-get update
sudo apt-get upgrade

echo "* Install dependencies"

sudo apt-get install build-essential libgtk2.0-dev libjpeg-dev libtiff4-dev libjasper-dev libopenexr-dev cmake python-dev python-numpy python-tk libtbb-dev libeigen3-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev libqt4-dev libqt4-opengl-dev sphinx-common texlive-latex-extra libv4l-dev libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev default-jdk ant libvtk5-qt4-dev


echo "* Get the OpenCV 2.4.9 source code"

cd ~
wget http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.9/opencv-2.4.9.zip
unzip opencv-2.4.9.zip
cd opencv-2.4.9

echo "* Compile dependencies"

mkdir build
cd build
cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_VTK=ON ..
make
sudo make install

echo "* More other configurations"

sudo chmod 777 /etc/ld.so.conf.d/opencv.conf
echo '/usr/local/lib' >> /etc/ld.so.conf.d/opencv.conf
sudo chmod 644 /etc/ld.so.conf.d/opencv.conf
sudo ldconfig

sudo chmod 777 /etc/bash.bashrc
cat <<EOT >> /etc/bash.bashrc
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH
EOT
sudo chmod 644 /etc/bash.bashrc

sudo reboot ##Reboot your system


